<?php

/**
 * Vercel PHP serverless entry point for Laravel.
 *
 * Vercel's filesystem is read-only at runtime (except /tmp).
 * We redirect all writable paths to /tmp so Laravel can compile
 * views, write logs, and manage the session cache.
 */

define('LARAVEL_START', microtime(true));

// ---------------------------------------------------------------------------
// CORS preflight — handle OPTIONS before Laravel boots for speed and reliability.
// Mirrors the allowed-origins rules in config/cors.php.
// ---------------------------------------------------------------------------
if (isset($_SERVER['REQUEST_METHOD']) && $_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    $origin = $_SERVER['HTTP_ORIGIN'] ?? '';

    $exactOrigins = [
        'http://localhost:3000',
        'http://localhost:3001',
        'http://192.168.0.12:3000',
        'https://taskflow-frontend-production-9467.up.railway.app',
    ];

    // Covers all Vercel preview & production deployments for this project
    $patternOrigin = '#^https://taskflow[a-z0-9\-]*\.vercel\.app$#';

    if (in_array($origin, $exactOrigins, true) || preg_match($patternOrigin, $origin)) {
        header("Access-Control-Allow-Origin: {$origin}");
        header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With, X-XSRF-TOKEN, Accept');
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Max-Age: 3600');
        http_response_code(204);
        exit();
    }
}

// ---------------------------------------------------------------------------
// Bootstrap writable directories in /tmp for Vercel's read-only filesystem
// ---------------------------------------------------------------------------
$tmpStorage      = '/tmp/storage';
$tmpBootstrapPath  = '/tmp/bootstrap';        // used with useBootstrapPath()
$tmpBootstrapCache = '/tmp/bootstrap/cache';  // cache sub-directory

foreach ([
    "$tmpStorage/framework/cache/data",
    "$tmpStorage/framework/sessions",
    "$tmpStorage/framework/views",
    "$tmpStorage/logs",
    "$tmpStorage/app",
    $tmpBootstrapCache,
] as $dir) {
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
}

// Copy any pre-built bootstrap cache files to /tmp so they survive at runtime.
// (packages.php may be generated by composer post-install scripts during build.)
$projectBootstrapCache = __DIR__ . '/../bootstrap/cache';
foreach (['packages.php', 'services.php'] as $cacheFile) {
    $src = "$projectBootstrapCache/$cacheFile";
    $dst = "$tmpBootstrapCache/$cacheFile";
    if (file_exists($src) && !file_exists($dst)) {
        copy($src, $dst);
    }
}

require __DIR__ . '/../vendor/autoload.php';

$app = require_once __DIR__ . '/../bootstrap/app.php';

// Redirect storage to /tmp so Laravel can write at runtime
$app->useStoragePath($tmpStorage);

// Redirect the bootstrap path so PackageManifest and ProviderRepository
// read/write packages.php and services.php from /tmp (writable).
// useBootstrapPath() expects the *parent* of cache/ — i.e. /tmp/bootstrap.
$app->useBootstrapPath($tmpBootstrapPath);

// Re-bind PackageManifest with the updated path so it uses the new
// getCachedPackagesPath() → /tmp/bootstrap/cache/packages.php
$app->instance(
    \Illuminate\Foundation\PackageManifest::class,
    new \Illuminate\Foundation\PackageManifest(
        new \Illuminate\Filesystem\Filesystem,
        $app->basePath(),
        $app->getCachedPackagesPath()
    )
);

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);
